import type { CreatureDef, PlaceDef, RandomEventDef, SpellDef } from "./gameData";

export const CREATURES: CreatureDef[] = [
  {
    id: "mole",
    name: "Mole",
    emoji: "🦡",
    elementId: "earth",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A small burrower that tunnels through soil, surfacing only when disturbed.",
  },
  {
    id: "salamander",
    name: "Salamander",
    emoji: "🦎",
    elementId: "fire",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A slick-skinned lizard that basks contentedly atop sun-warmed embers.",
  },
  {
    id: "goldfish",
    name: "Goldfish",
    emoji: "🐠",
    elementId: "water",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A bright, darting fish that flashes orange beneath the current.",
  },
  {
    id: "hawk",
    name: "Hawk",
    emoji: "🦅",
    elementId: "air",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A sharp-eyed hunter that rides the updrafts, watching the ground below.",
  },
  {
    id: "bee",
    name: "Bee",
    emoji: "🐝",
    elementId: "plant",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A fuzzy forager humming between blossoms, never straying far from the hive.",
  },
  {
    id: "pig",
    name: "Pig",
    emoji: "🐷",
    elementId: "mud",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A round, contented wallower that roots through the muck for anything edible.",
  },
  {
    id: "penguin",
    name: "Penguin",
    emoji: "🐧",
    elementId: "ice",
    level: 1,
    rarity: 2,
    isMagical: false,
    description:
      "A tuxedoed waddler that shrugs off the cold and belly-slides across the ice for fun.",
  },
  {
    id: "eel",
    name: "Eel",
    emoji: "🐟",
    elementId: "lightning",
    level: 1,
    rarity: 2,
    isMagical: false,
    description:
      "A sinuous swimmer that crackles with a charge, stunning anything foolish enough to touch it.",
  },
  {
    id: "crab",
    name: "Crab",
    emoji: "🦀",
    elementId: "sand",
    level: 1,
    rarity: 2,
    isMagical: false,
    description:
      "A sideways scuttler that buries itself in warm grit, claws poised just below the surface.",
  },
  {
    id: "firefly",
    name: "Firefly",
    emoji: "🪲",
    elementId: "light",
    level: 1,
    rarity: 3,
    isMagical: false,
    description:
      "A drifting glow that blinks its soft lantern through the dark, speaking in flashes.",
  },
  {
    id: "cat",
    name: "Cat",
    emoji: "🐱",
    elementId: "darkness",
    level: 1,
    rarity: 3,
    isMagical: false,
    description: "A silent prowler that melts into shadow, seen only when its eyes catch the moon.",
  },
  {
    id: "skunk",
    name: "Skunk",
    emoji: "🦨",
    elementId: "poison",
    level: 1,
    rarity: 3,
    isMagical: false,
    description:
      "A bold little forager that ambles without fear, trusting the warning of its noxious spray.",
  },
  {
    id: "cricket",
    name: "Cricket",
    emoji: "🦗",
    elementId: "sound",
    level: 1,
    rarity: 4,
    isMagical: false,
    description: "A tireless chirper whose song fills the night, felt as much as heard.",
  },
  {
    id: "dog",
    name: "Dog",
    emoji: "🐶",
    elementId: "force",
    level: 1,
    rarity: 5,
    isMagical: false,
    description:
      "A loyal powerhouse that bowls over anything in its path, tail wagging the whole time.",
  },
  {
    id: "dragonfly",
    name: "Dragonfly",
    emoji: "🦋",
    elementId: "time",
    level: 1,
    rarity: 5,
    isMagical: false,
    description:
      "A shimmering darter that seems to hover between moments, wings a blur of borrowed seconds.",
  },
  {
    id: "seaturtle",
    name: "Sea Turtle",
    emoji: "🐢",
    elementId: "space",
    level: 1,
    rarity: 5,
    isMagical: false,
    description:
      "An ancient drifter that glides through open water as if swimming among the stars.",
  },
  {
    id: "rabbit",
    name: "Rabbit",
    emoji: "🐰",
    elementId: "love",
    level: 1,
    rarity: 6,
    isMagical: false,
    description:
      "A soft-hearted hopper that gathers others close, multiplying warmth wherever it nests.",
  },
  {
    id: "chicken",
    name: "Chicken",
    emoji: "🐔",
    elementId: "life",
    level: 1,
    rarity: 7,
    isMagical: false,
    description:
      "A humble layer whose every egg holds a small, stubborn promise of new beginnings.",
  },
  {
    id: "fox",
    name: "Fox",
    emoji: "🦊",
    elementId: "magic",
    level: 1,
    rarity: 7,
    isMagical: false,
    description: "A cunning trickster whose grin hints it knows a secret the world has forgotten.",
  },
  {
    id: "crow",
    name: "Crow",
    emoji: "🐦‍⬛",
    elementId: "death",
    level: 1,
    rarity: 7,
    isMagical: false,
    description: "A glossy watcher that gathers at endings, carrying off what others leave behind.",
  },
  {
    id: "cinderling",
    name: "Cinderling",
    emoji: "🔥",
    elementId: "fire",
    level: 2,
    rarity: 3,
    isMagical: true,
    consumedElementId: "plant",
    producedElementId: "fire",
    description: "A tiny ember spirit that eats dry leaves and coughs up glittering sparks.",
  },
  {
    id: "sylf",
    name: "Sylf",
    emoji: "💨",
    elementId: "air",
    level: 2,
    rarity: 3,
    isMagical: true,
    consumedElementId: "water",
    producedElementId: "air",
    description: "A quick-winged air spirit that drinks mist and leaves restless breezes behind.",
  },
  {
    id: "dryad",
    name: "Dryad",
    emoji: "🌿",
    elementId: "plant",
    level: 2,
    rarity: 3,
    isMagical: true,
    consumedElementId: "earth",
    producedElementId: "plant",
    description:
      "A young grove spirit that draws strength from soil and coaxes fresh growth from it.",
  },
  {
    id: "troll",
    name: "Troll",
    emoji: "🧌",
    elementId: "earth",
    level: 4,
    rarity: 3,
    isMagical: true,
    consumedElementId: "plant",
    producedElementId: "earth",
    description:
      "A hulking moss-backed brute that chews through bramble and packs the ground hard beneath its tread.",
  },
  {
    id: "nyad",
    name: "Nyad",
    emoji: "🧜",
    elementId: "water",
    level: 2,
    rarity: 3,
    isMagical: true,
    consumedElementId: "air",
    producedElementId: "water",
    description:
      "A shy spring spirit that breathes in the morning mist and lets it trickle back as clear water.",
  },
];

export const SPELLS: SpellDef[] = [
  {
    id: "flaming-dart",
    name: "Flaming Dart",
    emoji: "🔥",
    elementId: "fire",
    kind: "direct",
    unlockLevel: 1,
    power: 3,
    description: "A bolt of searing flame hurled at the foe, dealing immediate burn damage.",
  },
  {
    id: "drown",
    name: "Drown",
    emoji: "🌊",
    elementId: "water",
    kind: "dot",
    unlockLevel: 1,
    power: 2,
    durationRounds: 3,
    description: "Water floods the target's lungs, damaging them now and for 2 more rounds.",
  },
  {
    id: "eartharmor",
    name: "Eartharmor",
    emoji: "🛡️",
    elementId: "earth",
    kind: "utility",
    unlockLevel: 1,
    power: 2,
    utilityKind: "shield",
    description:
      "Coats your skin in stone, reducing the next hit you take by power × level before crumbling away.",
  },
  {
    id: "flight",
    name: "Flight",
    emoji: "🕊️",
    elementId: "air",
    kind: "utility",
    unlockLevel: 1,
    power: 3,
    utilityKind: "haste",
    hasteDurationMs: 600_000,
    description:
      "Lifts you on the wind for 10 minutes, shortening gathering cooldowns by element level × power seconds.",
  },
  {
    id: "tangle",
    name: "Tangle",
    emoji: "🪢",
    elementId: "plant",
    kind: "dot",
    unlockLevel: 1,
    power: 3,
    durationRounds: 3,
    halvesRetaliation: true,
    description:
      "Creeping vines bind the target, damaging it over time and halving its strikes while entangled.",
  },
  {
    id: "zap",
    name: "Zap",
    emoji: "⚡",
    elementId: "lightning",
    kind: "direct",
    unlockLevel: 1,
    power: 3,
    description: "A sharp jolt of lightning that strikes the foe instantly for immediate damage.",
  },
  {
    id: "poison-spray",
    name: "Poison Spray",
    emoji: "🧪",
    elementId: "poison",
    kind: "dot",
    unlockLevel: 1,
    power: 2,
    durationRounds: 3,
    description: "A noxious mist that sickens the target, damaging it now and for 2 more rounds.",
  },
];

export const PLACES: PlaceDef[] = [
  {
    id: "forest",
    name: "Forest",
    emoji: "🌲",
    kind: "forest",
    rarity: 1,
    description: "A dense woodland. Gather wood here.",
  },
  {
    id: "stone-mine",
    name: "Stone Mine",
    emoji: "⛏️",
    kind: "stone_mine",
    rarity: 1,
    description: "A rocky mine shaft. Gather stone here.",
  },
  {
    id: "ember-grove",
    name: "Ember Grove",
    emoji: "🔥",
    kind: "elemental",
    elementId: "fire",
    rarity: 2,
    description: "A grove where embers smolder in the underbrush.",
  },
  {
    id: "flowing-stream",
    name: "Flowing Stream",
    emoji: "💧",
    kind: "elemental",
    elementId: "water",
    rarity: 2,
    description: "A clear stream winding through the land.",
  },
  {
    id: "tall-mountain",
    name: "Tall Mountain",
    emoji: "⛰️",
    kind: "elemental",
    elementId: "earth",
    rarity: 2,
    description: "A towering peak of solid rock.",
  },
  {
    id: "high-up-a-tree",
    name: "High Up a Tree",
    emoji: "🌳",
    kind: "elemental",
    elementId: "air",
    rarity: 2,
    description: "A perch high above the ground, open to the wind.",
  },
  {
    id: "grassy-planes",
    name: "Grassy Planes",
    emoji: "🌾",
    kind: "elemental",
    elementId: "plant",
    rarity: 2,
    description: "Rolling fields of wild grass stretching to the horizon.",
  },
  {
    id: "muddy-bog",
    name: "Muddy Bog",
    emoji: "🟫",
    kind: "elemental",
    elementId: "mud",
    rarity: 2,
    description: "A waterlogged hollow thick with mud underfoot.",
  },
  {
    id: "glacier",
    name: "Glacier",
    emoji: "🧊",
    kind: "elemental",
    elementId: "ice",
    rarity: 3,
    description: "A vast wall of ancient ice, groaning as it inches forward.",
  },
  {
    id: "storm-cloud",
    name: "Storm Cloud",
    emoji: "⛈️",
    kind: "elemental",
    elementId: "lightning",
    rarity: 3,
    description: "A churning thunderhead crackling with restless charge.",
  },
  {
    id: "desert-dunes",
    name: "Desert Dunes",
    emoji: "🏜️",
    kind: "elemental",
    elementId: "sand",
    rarity: 3,
    description: "Endless rolling dunes that hiss and shift with every gust.",
  },
  {
    id: "sunlit-clearing",
    name: "Sunlit Clearing",
    emoji: "🌅",
    kind: "elemental",
    elementId: "light",
    rarity: 4,
    description: "A bright glade where sunbeams pool warm on the grass.",
  },
  {
    id: "shadow-cavern",
    name: "Shadow Cavern",
    emoji: "🕳️",
    kind: "elemental",
    elementId: "darkness",
    rarity: 4,
    description: "A lightless hollow where the dark gathers thick and still.",
  },
  {
    id: "toxic-bog",
    name: "Toxic Bog",
    emoji: "☣️",
    kind: "elemental",
    elementId: "poison",
    rarity: 4,
    description: "A festering marsh that bubbles with acrid, stinging fumes.",
  },
  {
    id: "echoing-canyon",
    name: "Echoing Canyon",
    emoji: "🏞️",
    kind: "elemental",
    elementId: "sound",
    rarity: 5,
    description: "A deep ravine that throws every whisper back a hundredfold.",
  },
  {
    id: "gravity-well",
    name: "Gravity Well",
    emoji: "🌀",
    kind: "elemental",
    elementId: "force",
    rarity: 6,
    description: "A churning pit where unseen force drags everything inward.",
  },
  {
    id: "time-vortex",
    name: "Time Vortex",
    emoji: "🕰️",
    kind: "elemental",
    elementId: "time",
    rarity: 6,
    description: "A spinning rift where moments tumble loose and scatter.",
  },
  {
    id: "astral-void",
    name: "Astral Void",
    emoji: "🌌",
    kind: "elemental",
    elementId: "space",
    rarity: 6,
    description: "A silent expanse of stars stretching past the edge of sight.",
  },
  {
    id: "heartspring-grotto",
    name: "Heartspring Grotto",
    emoji: "💞",
    kind: "elemental",
    elementId: "love",
    rarity: 7,
    description: "A hidden hollow where a warm spring murmurs and glows.",
  },
  {
    id: "thriving-rainforest",
    name: "Thriving Rainforest",
    emoji: "🌴",
    kind: "elemental",
    elementId: "life",
    rarity: 8,
    description: "A lush canopy teeming and breathing with relentless growth.",
  },
  {
    id: "faerie-ring",
    name: "Faerie Ring",
    emoji: "🍄",
    kind: "elemental",
    elementId: "magic",
    rarity: 8,
    description: "A ring of toadstools humming faintly with old enchantment.",
  },
  {
    id: "graveyard",
    name: "Graveyard",
    emoji: "🪦",
    kind: "elemental",
    elementId: "death",
    rarity: 8,
    description: "A quiet field of leaning stones where the air hangs heavy.",
  },
];

export const RANDOM_EVENTS: RandomEventDef[] = [];
