import type { CreatureDef, PlaceDef, RandomEventDef, SpellDef } from "./gameData";

export const CREATURES: CreatureDef[] = [
  {
    id: "mole",
    name: "Mole",
    emoji: "🦡",
    elementId: "earth",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A small burrower that tunnels through soil, surfacing only when disturbed.",
  },
  {
    id: "salamander",
    name: "Salamander",
    emoji: "🦎",
    elementId: "fire",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A slick-skinned lizard that basks contentedly atop sun-warmed embers.",
  },
  {
    id: "goldfish",
    name: "Goldfish",
    emoji: "🐠",
    elementId: "water",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A bright, darting fish that flashes orange beneath the current.",
  },
  {
    id: "hawk",
    name: "Hawk",
    emoji: "🦅",
    elementId: "air",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A sharp-eyed hunter that rides the updrafts, watching the ground below.",
  },
  {
    id: "bee",
    name: "Bee",
    emoji: "🐝",
    elementId: "plant",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A fuzzy forager humming between blossoms, never straying far from the hive.",
  },
  {
    id: "pig",
    name: "Pig",
    emoji: "🐷",
    elementId: "mud",
    level: 1,
    rarity: 1,
    isMagical: false,
    description: "A round, contented wallower that roots through the muck for anything edible.",
  },
];

export const SPELLS: SpellDef[] = [
  {
    id: "flaming-dart",
    name: "Flaming Dart",
    emoji: "🔥",
    elementId: "fire",
    kind: "direct",
    unlockLevel: 1,
    power: 3,
    description: "A bolt of searing flame hurled at the foe, dealing immediate burn damage.",
  },
  {
    id: "drown",
    name: "Drown",
    emoji: "🌊",
    elementId: "water",
    kind: "dot",
    unlockLevel: 1,
    power: 2,
    durationRounds: 3,
    description: "Water floods the target's lungs, damaging them now and for 2 more rounds.",
  },
  {
    id: "eartharmor",
    name: "Eartharmor",
    emoji: "🛡️",
    elementId: "earth",
    kind: "utility",
    unlockLevel: 1,
    power: 2,
    utilityKind: "shield",
    description:
      "Coats your skin in stone, reducing the next hit you take by power × level before crumbling away.",
  },
  {
    id: "flight",
    name: "Flight",
    emoji: "🕊️",
    elementId: "air",
    kind: "utility",
    unlockLevel: 1,
    power: 3,
    utilityKind: "haste",
    hasteDurationMs: 600_000,
    description:
      "Lifts you on the wind for 10 minutes, shortening gathering cooldowns by element level × power seconds.",
  },
  {
    id: "tangle",
    name: "Tangle",
    emoji: "🪢",
    elementId: "plant",
    kind: "dot",
    unlockLevel: 1,
    power: 3,
    durationRounds: 3,
    halvesRetaliation: true,
    description:
      "Creeping vines bind the target, damaging it over time and halving its strikes while entangled.",
  },
];

export const PLACES: PlaceDef[] = [
  {
    id: "forest",
    name: "Forest",
    emoji: "🌲",
    kind: "forest",
    rarity: 1,
    description: "A dense woodland. Gather wood here.",
  },
  {
    id: "stone-mine",
    name: "Stone Mine",
    emoji: "⛏️",
    kind: "stone_mine",
    rarity: 1,
    description: "A rocky mine shaft. Gather stone here.",
  },
  {
    id: "ember-grove",
    name: "Ember Grove",
    emoji: "🔥",
    kind: "elemental",
    elementId: "fire",
    rarity: 1,
    description: "A grove where embers smolder in the underbrush.",
  },
  {
    id: "flowing-stream",
    name: "Flowing Stream",
    emoji: "💧",
    kind: "elemental",
    elementId: "water",
    rarity: 1,
    description: "A clear stream winding through the land.",
  },
  {
    id: "tall-mountain",
    name: "Tall Mountain",
    emoji: "⛰️",
    kind: "elemental",
    elementId: "earth",
    rarity: 1,
    description: "A towering peak of solid rock.",
  },
  {
    id: "high-up-a-tree",
    name: "High Up a Tree",
    emoji: "🌳",
    kind: "elemental",
    elementId: "air",
    rarity: 1,
    description: "A perch high above the ground, open to the wind.",
  },
  {
    id: "grassy-planes",
    name: "Grassy Planes",
    emoji: "🌾",
    kind: "elemental",
    elementId: "plant",
    rarity: 1,
    description: "Rolling fields of wild grass stretching to the horizon.",
  },
  {
    id: "muddy-bog",
    name: "Muddy Bog",
    emoji: "🟫",
    kind: "elemental",
    elementId: "mud",
    rarity: 1,
    description: "A waterlogged hollow thick with mud underfoot.",
  },
];

export const RANDOM_EVENTS: RandomEventDef[] = [];
